### ISSUE TITLE
Add tray support to the application

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku-desktop#12]
On closing the main window the app should keep running in the system tray and keep playing the tracks in the background unless the user exits from the tray.

**Comment by coderjoe** [comment]
I gave this a shot. Clicking the tray hides and shows the application. Closing the main window hides the application. The application can be quit from the context menu for the tray icon.

Unfortunately I have no graphic design skill so there's a placeholder icon for the tray right now. I'm hoping issue #14 will replace the icon with a more permanent version.

Please let me know if there's anything you'd like changed. :)

**Comment by anshumanv** [comment]
Hey, @coderjoe thanks so much for your contribution. 😄 
Please follow up the discussion on the PR.
