### ISSUE TITLE
Add desktop notifications to the app

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku-desktop#13]
The app should throw desktop notifications when the track changes and should display the track name.

**Comment by SoldierCorp** [comment]
Hello, I'll help you with this.

**Comment by anshumanv** [comment]
Sure @SoldierCorp, go for it. 👍

**Comment by SoldierCorp** [comment]
Thanks @anshumanv but I just realised that you are using a webview and is not possible to detect any event as far as I know, or is it possible?

Because I was trying with jquery but is not getting the children elements of the webview.

**Comment by anshumanv** [comment]
You need to use webview api for this https://electron.atom.io/docs/api/webview-tag/
I think it should be possible.

**Comment by anshumanv** [comment]
Perhaps I found a repo that does this - https://github.com/JavaScriptDude/Electron-Webview-Host-to-Guest-RPC-Sample

**Comment by zdoc01** [comment]
@anshumanv @SoldierCorp - I found a way to do this with a preload script and opened a PR. Let me know if you have any questions!
